### ISSUE TITLE
[URGENT] Change “preferred” full name to legal full name 

### ISSUE THREAD

**Issue by elenalape** [compsoc-edinburgh/hackassistant-registration#14]
People shouldn’t put a preferred full name, change text to “As written in your identification documents” or similar. Upon registration

**Comment by qaisjp** [comment]
Don't agree with this one.

Also, in Scotland, _I believe_ your name is the name you go by, even if you haven't had your passport updated yet.

When checking IDs, we don't need to be dicks and say "well the photo and surname seems to match, but your forename is different, so go away."

**Comment by alistairmackenzie** [comment]
For Scotland (where the event is being held) Section 43 of the [Registration of Births, Deaths and Marriages (Scotland) Act 1965](https://www.legislation.gov.uk/ukpga/1965/49/section/43) will point out that it is perfectly fine to change your name in Scotland both with and without documentation. The identification documents are slightly more formal to change. This can be read in more simpler terms if you prefer [here](https://www.citizensadvice.2org.uk/scotland/family/birth-certificates-and-changing-your-name-s/changing-your-name-s/) and [here](https://brodies.com/blog/family-law/changing-name-scotland/) This applies for both your forename and surname.

People are fully entitiled to have a _prefered_ name regardless of the documentation to support it legally or not in any country, not just in Scotland.

Unless official ID is being checked at the event I do not see why this is necessary. As far as I'm aware only student ID is checked which at Edinburgh does not even have your forename on the card.

In my opinion, I see this as your own personal issue with prefered names which is not applicable to this event.

**Comment by elenalape** [comment]
> Unless official ID is being checked at the event I do not see why this is necessary. As far as I'm aware only student ID is checked which at Edinburgh does not even have your forename on the card.
Yes, we will check official IDs, and so do most hackathons, definitely Hack Cambridge, all of international hackathons. There are legitimate reasons we have to do this: firstly, we need to make sure they are not under 18, and also, we need to know exactly who is in the building. The way to do it is to check what name is written on their official IDs. This has been made very clear to us.
> In my opinion, I see this as your own personal issue with prefered names which is not applicable to this event.
:) I changed my name 2 years ago and boy did I wish I could have started using it earlier. This isn't personal at all, this is a requirement we have to fulfill.

**Comment by elenalape** [comment]
@alistairmackenzie 
>
> Unless official ID is being checked at the event I do not see why  this is necessary. As far as I'm aware only student ID is checked which  at Edinburgh does not even have your forename on the card.
>
Yes, we will check official IDs, and so do most hackathons, definitely  Hack Cambridge, all of international hackathons. There are legitimate  reasons we have to do this: firstly, we need to make sure they are not  under 18, and also, we need to know exactly who is in the building. The  way to do it is to check what name is written on their official IDs. This has been made very clear to us.

>
> In my opinion, I see this as your own personal issue with prefered names which is not applicable to this event.
>
:) I changed my name 2 years ago and boy did I wish I could have started  using it earlier. This isn't personal at all, this is a requirement we  have to fulfill.

**Comment by elenalape** [comment]
@qaisjp 
>
> When checking IDs, we don't need to be dicks and say "well the photo and surname seems to match, but your forename is different, so go away."
>
Sure, if you know them personally it's not an issue at all. But let's keep things official.

**Comment by vaidap** [comment]
One way to do this, if you really need to check IDs is ask for the full legal name, stating that this will only be used to check for age/identity on their ID, and not be public; and ask for a preferred name that will be used in profile/communications. Not allowing people to specify their preferred name isn't very inclusive (trans individuals) or usable (eg. people with complicated names that are recognised by friends through a shorter version).

**Comment by elenalape** [comment]
@vaidap 
> One way to do this, if you really need to check IDs is ask for the full legal name, stating that this will only be used to check for age/identity on their ID, and not be public; and ask for a preferred name that will be used in profile/communications. Not allowing people to specify their preferred name isn't very inclusive (trans individuals) or usable (eg. people with complicated names that are recognised by friends through a shorter version).

Agree with this comment, just wondering how to not overload the registration form. Can we have legal name and then preferred name? @qaisjp

**Comment by qaisjp** [comment]
> we need to make sure they are not under 18 [.. ] Sure, if you know them personally it's not an issue at all. But let's keep things official.

Having both student ID (confirms they are a student perfectly well, regardless of forename), and legal documents (perfectly easy to check birthdate and cross reference photo/surname).

I don't think being reasonable is something we should limit to people we know. The university is _not_ going to turn around and ban us for using someone's preferred name.

> we need to know exactly who is in the building. The way to do it is to check what name is written on their official IDs. This has been made very clear to us.

I have just checked with Neil Heatley and he says he has never heard of this requirement for full legal name @ the venue. Are you sure school office is requesting this?

> ask for both legal and preferred name

Vaida's suggestion is possible, but a pain to do now. There is the problem of dealing with the 100 (yes, exactly 100) accounts that have already registered. I still think this issue is unnecessary.

This has never been a problem in the past, even at other hackathons. I can't see any reason to be rigid.

**Comment by elenalape** [comment]
@qaisjp Uhh... "Of course we need to know. Qais asked me a question out of context"

I'll check with the School Office though. However, we still need an ID verification for the age...

**Comment by Visgean** [comment]
Migration on this should be super easy btw. Just add getter on name, if the preferred name is defined, return that. Otherwise default to legal name

**Comment by qaisjp** [comment]
@elenalape I was clear to him that I was talking about hackathon attendees. I've also confirmed with him, in person, that he has never heard about this requirement.

@visgean the idea would be to keep preferred name as it is now, and add an extra "legal_name" field. Problem here is that we can't just set legal name to preferred name for existing accounts because they could be different. There's also no existing way for users to update their account details atm. We could write an extra tab but then we can't (well, we shouldn't) really email everyone saying "please set your legal name". 

All in all, on the day, if we find a name mismatch, a volunteer can just write it down on paper.

**Comment by elenalape** [comment]
At the end of the day, having their legal name is a risk control measure. People are coming in from all over the UK -- we need to know their full names, and we will be checking their government IDs.

Please add the government ID legal name field. Not for the current applicants, let's assume most of them are the same, but for the next 400.

**Comment by neilheatley** [comment]
Hi, 
Please don't quote private correspondace with me. I was not given a full explained question to speak and at all times pointed to say questions should be directed to the School Office who act as 'the venue'. 
I am alsways happy to try and help resolve issues, however do not act as a representative of 'the venue'.
Neil

**Comment by JammyStuff** [comment]
Given that the UK has no Government issued photo ID that people would be required to have, is there a plan for people who don't have a passport or driving licence? 24% of people born in the UK have no passport, and 10 million UK nationals don't have a driving licence. It seems likely that there would be some overlap between those two groups, and that overlap is likely to be mostly poorer.

It's not the intention, but this policy has the possibility of excluding people who would otherwise meet all of the requirements of taking part.

**Comment by elenalape** [comment]
@JammyStuff I'd like to know how you can make it to the University to study computer science without having an ID, and also how as a uni student you never encounter a situation where you'd need an ID other than your birth certificate. Come on man.

**Comment by JammyStuff** [comment]
@elenalape I'm not sure how I'm supposed to answer that. What would stop someone who was born in the UK and didn't drive from getting in to University to study Computer Science? You're making it sound like it's an impossible scenario, but last time I checked doing well enough at your exams to get in to University didn't require travel out of the country or the ability to drive. Pretty much everything else offers an alternative.

**Comment by elenalape** [comment]
Thank you everybody for your input, I think we have covered enough and the issue of adding a single extra field or modifying the current one has turned into something completely different, so I am closing it. 
The adding of the extra field will be discussed within the actual organising committee.

**Comment by qaisjp** [comment]
(oops)
